name: "Deploy to Ali-OSS"
description: "Greet someone and record the time"
inputs:
  oss_id: # id of input
    description: "Who to greet"
    required: true
    default: null
  oss_secret:
    description: ""
    required: true
    default: null
  bucket:
    description: ""
    required: true
    default: null
  ssl:
    description: ""
    required: false
    default: true
  files:
    description: ""
  dirs:
    description: ""
runs:
  using: "node12"
  main: "dist/index.js"
